name: Update Homebrew Formula

on:
  release:
    types:
      - created
      - updated

jobs:
  update_formula:
    runs-on: ubuntu-latest

    steps:
      - name: Check out tap repository
        uses: actions/checkout@v2
        with:
          repository: jsoconno/homebrew-terraflow
          token: ${{ secrets.HOMEBREW }}
          path: homebrew-tap

      - name: Update formula
        run: |
          FORMULA_PATH="homebrew-tap/Formula/terraflow.rb"
          VERSION="${{ github.event.release.tag_name }}"
          URL="https://github.com/jsoconno/terraflow/archive/${VERSION}.tar.gz"
          SHA256="$(curl -L -s ${URL} | sha256sum | awk '{print $1}')"
          sed -i "s|url .\+|url \"$URL\"|g" $FORMULA_PATH
          sed -i "s|sha256 .\+|sha256 \"$SHA256\"|g" $FORMULA_PATH

      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/terraflow.rb
          git commit -m "Update terraflow to ${{ github.event.release.tag_name }}"
          git push
